
ALL: 
    nmake /nologo /s /f DOSXXX.MAK
    nmake /nologo /s /f DOSCALLS.MAK
    nmake /nologo /s /f NLS.MAK
    nmake /nologo /s /f VIOCALLS.MAK
    nmake /nologo /s /f KBDCALLS.MAK
#   nmake /nologo /s /f MOUCALLS.MAK

clean: 
    nmake /nologo /s /f DOSXXX.MAK    clean
    nmake /nologo /s /f DOSCALLS.MAK  clean
    nmake /nologo /s /f NLS.MAK       clean
    nmake /nologo /s /f VIOCALLS.MAK  clean
    nmake /nologo /s /f KBDCALLS.MAK  clean
#   nmake /nologo /s /f MOUCALLS.MAK  clean
